# Generated by Django 3.0 on 2022-08-27 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='organisation',
        ),
    ]
